# Generated by Django 2.1.5 on 2019-01-19 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='topics',
            new_name='status',
        ),
    ]
