# Generated by Django 2.1.5 on 2019-01-19 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20190119_0644'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
