# Generated by Django 2.1.5 on 2019-01-19 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topics', models.CharField(blank=True, max_length=50, null=True)),
                ('is_delete', models.BooleanField(default=False)),
            ],
        ),
    ]
